tap "nikitabobko/tap"

brew "bat"
brew "direnv"
brew "dotdrop"
brew "duf"
brew "dust"
brew "eza"
brew "fd"
brew "fish"
brew "fx"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "go"
brew "helix"
brew "hyperfine"
brew "jq"
brew "lazygit"
brew "mas"
brew "marksman"
brew "opencode"
brew "openvpn"
brew "ripgrep"
brew "shellcheck"
brew "tmux"
brew "tokei"
brew "tree"
brew "watch"
brew "yq"
brew "zoxide"

cargo "felix"

cask "nikitabobko/tap/aerospace", trusted: true
cask "1password"
cask "1password-cli"
cask "raycast"
cask "font-fantasque-sans-mono"
cask "karabiner-elements"
cask "kitty"
cask "microsoft-teams"
cask "spotify"
cask "helium-browser"
