[main]
term=foot
font=Fantasque Sans Mono:size=14
dpi-aware=yes
font-bold=Fantasque Sans Mono:size=14:weight=bold
pad=10x10

[bell]
urgent=no
notify=no

[scrollback]
lines=10000

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

[colors-dark]
# >>> chromasync
background=000000
foreground=bababa

selection-foreground=000000
selection-background=535353

regular0=000000  # black
regular1=e83731  # red
regular2=009500  # green
regular3=7b8200  # yellow
regular4=745dff  # blue
regular5=d521d6  # magenta
regular6=008e90  # cyan
regular7=474747  # white

bright0=262626  # bright black
bright1=ff7460  # bright red
bright2=04cd13  # bright green
bright3=b5b700  # bright yellow
bright4=b591ff  # bright blue
bright5=ff69ff  # bright magenta
bright6=00c5c5  # bright cyan
bright7=606060  # bright white
# <<< chromasync
 
[tweak]
delayed-render-lower=0
delayed-render-upper=0
