for_window [class="^osu!$"] allow_tearing yes
for_window [title="^osu!"] allow_tearing yes
for_window [app_id="osu!"] allow_tearing yes
for_window [title="osu!lazer"] allow_tearing yes

assign [app_id="helium"] workspace number 1
assign [app_id="discord"] workspace number 8
assign [class="discord"] workspace number 8
assign [class="Spotify"] workspace number 9

exec helium-browser
exec discord
exec spotify-launcher
exec 1password --silent
