include fonts.conf

scrollback_lines 20000

window_padding_width 10
placement_strategy center
remember_window_size yes
hide_window_decorations titlebar-only

macos_option_as_alt both
macos_traditional_fullscreen yes

cursor_shape block
cursor_shape_unfocused hollow
cursor_blink_interval 0
# cursor_trail 3
shell_integration enabled no-cursor

copy_on_select clipboard
strip_trailing_spaces smart
mouse_hide_wait -1.0
focus_follows_mouse no
confirm_os_window_close -1

# background_opacity 0.94
# background_blur 24
# inactive_text_alpha 0.85

allow_hyperlinks yes
url_style dotted

map ctrl+shift+p command_palette
map ctrl+shift+y kitten themes --config-file-name theme.conf
map ctrl+shift+u kitten hints
map ctrl+shift+f search_scrollback
map ctrl+shift+g show_last_command_output


# BEGIN_KITTY_THEME
# Arthur
include current-theme.conf
# END_KITTY_THEME
