package theme

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/BurntSushi/toml"
)

func TestLoadsRepositoryThemeCatalog(t *testing.T) {
	root, err := filepath.Abs(filepath.Join("..", "..", "..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	if !validRoot(root) {
		t.Fatalf("%s is not recognized as the repository root", root)
	}

	names := themeNames(root)
	if len(names) < 20 {
		t.Fatalf("theme catalog contains %d themes, want at least 20", len(names))
	}
	for _, name := range names {
		if _, err := readTheme(root, name); err != nil {
			t.Fatalf("load theme %s: %v", name, err)
		}
	}
	theme := loadTheme(root, "carbonfox")
	if theme.ID != "carbonfox" || theme.Name != "carbonfox" || theme.Mode != "dark" {
		t.Fatalf("loaded theme = %+v", theme)
	}
	if theme.Colors["bg"] == "" || theme.Apps["helix"]["theme"] == "" {
		t.Fatalf("carbonfox theme is missing required values: %+v", theme)
	}
}

func TestThemeSelectionLivesOutsideRepository(t *testing.T) {
	root, err := filepath.Abs(filepath.Join("..", "..", "..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	defaultPath := filepath.Join(root, "themes", "default")
	before, err := os.ReadFile(defaultPath)
	if err != nil {
		t.Fatal(err)
	}

	config := t.TempDir()
	if got := selectedTheme(root, config); got != strings.TrimSpace(string(before)) {
		t.Fatalf("default selection = %q, want %q", got, strings.TrimSpace(string(before)))
	}
	useTheme(root, config, "kanagawa", false)
	if got := selectedTheme(root, config); got != "kanagawa" {
		t.Fatalf("selected theme = %q, want kanagawa", got)
	}
	after, err := os.ReadFile(defaultPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(after) != string(before) {
		t.Fatalf("repository default changed from %q to %q", before, after)
	}
}

func TestReadThemeRejectsUnknownThemeWithoutChangingSelection(t *testing.T) {
	root, err := filepath.Abs(filepath.Join("..", "..", "..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	config := t.TempDir()
	write(themeSelectionPath(config), "oxocarbon")

	if _, err := readTheme(root, "definitely-not-a-theme"); err == nil {
		t.Fatal("missing theme was accepted")
	}
	if got := selectedTheme(root, config); got != "oxocarbon" {
		t.Fatalf("selection changed to %q", got)
	}
}

func TestGenerateTmuxUsesThemePalette(t *testing.T) {
	root, err := filepath.Abs(filepath.Join("..", "..", "..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	theme := loadTheme(root, "oxocarbon")
	config := t.TempDir()
	generateTmux(config, theme)

	data, err := os.ReadFile(filepath.Join(config, "tmux", "theme.conf"))
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)
	for _, expected := range []string{
		"Generated by theme use oxocarbon",
		`set -g status 2`,
		`set -g status-justify absolute-centre`,
		`status-style "bg=default,fg=#f2f4f8"`,
		`status-format[0] '#[fg=#393939,bg=default]#{R:─,#{client_width}}'`,
		`status-left '#[fg=#78a9ff,bg=default,bold] #{?@ws-title,#{@ws-title},#S} #[fg=#f2f4f8,bg=default,nobold] '`,
		`window-status-current-format "#[fg=#78a9ff,bg=default,bold] #I #W "`,
		`pane-active-border-style "fg=#78a9ff"`,
		`@theme-popup-border "#393939"`,
		"client_prefix",
	} {
		if !strings.Contains(content, expected) {
			t.Fatalf("tmux theme does not contain %q:\n%s", expected, content)
		}
	}
	if strings.Contains(content, "bg=#0f0f0f") {
		t.Fatalf("tmux theme paints the status background:\n%s", content)
	}
}

func TestGenerateHelixKeepsModeStripOnEditorBackground(t *testing.T) {
	root, err := filepath.Abs(filepath.Join("..", "..", "..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	theme := loadTheme(root, "kanagawa")
	config := t.TempDir()
	generateHelix(config, theme)

	data, err := os.ReadFile(filepath.Join(config, "helix", "themes", "generated.toml"))
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)
	var parsed map[string]any
	if _, err := toml.Decode(content, &parsed); err != nil {
		t.Fatalf("generated Helix theme is invalid TOML: %v", err)
	}
	for _, expected := range []string{
		`inherits = "kanagawa"`,
		`"ui.statusline" = { fg = "generated_status_fg", bg = "generated_status_bg" }`,
		`"ui.statusline.inactive" = { fg = "generated_status_dim", bg = "generated_status_bg" }`,
		`"ui.statusline.normal" = { fg = "generated_mode_normal", bg = "generated_mode_bg", modifiers = ["bold"] }`,
		`"ui.statusline.insert" = { fg = "generated_mode_insert", bg = "generated_mode_bg", modifiers = ["bold"] }`,
		`"ui.statusline.select" = { fg = "generated_mode_select", bg = "generated_mode_bg", modifiers = ["bold"] }`,
		`generated_status_bg = "#1f1f28"`,
	} {
		if !strings.Contains(content, expected) {
			t.Fatalf("Helix theme does not contain %q:\n%s", expected, content)
		}
	}
}
